ssh se013 ""
ssh se014 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se052 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se053 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se054 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se055 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se056 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se057 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se058 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se059 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se060 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se061 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se062 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se063 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
ssh se064 "cd /localfs/xyao/ec-spark ; git clone se016:/localfs/xyao/ec-spark/spark-ecshuffle"
